### PR TITLE
WIP - Add phoenix emulator for atari jaguar

### PR DESCRIPTION
**Pull request by samiracho**
Add phoenix emulator (http://www.arts-union.ru/node/23) for jaguar. This emulator has a 95% compatibility with atari jaguar games and works much better than the libretro core.
The joypad configuration is missing, I'm working on it.  (By now I just hardcoded a xbox controller mapping).

In order to test it:

- Download phoenix emulator (russian) from http://www.arts-union.ru/sites/default/files/ph28jag-win64.zip and put it in the emulators folder.
- Optional, english translation (https://www.sendspace.com/file/03e6zt)
- Download atari jaguar bios "[BIOS] Atari Jaguar (World).j64" and put it in bios folder
- emulatorLauncher.exe" -system jaguar -emulator phoenix -core phoenix -rom "c:\roms\romname.j64"

### CODE REVIEW

**Comment by fabricecaruso** [comment]
What's up with the  .gitignore file ? Why so many changes ?

**Comment by samiracho** [comment]
I can revert the changes. I just tend to use the .gitignore from https://github.com/github/gitignore/blob/master/VisualStudio.gitignore on the visual studio projects to avoid pushing unwanted files.

**Comment by samiracho** [comment]
@fabricecaruso I'm struggling with the controls. How is the control mapping passed from emulationstation to emulatorlauncher. 
For example if the user has an xbox controller and sets the button mapping in Emulationstation to:
A > X
B > Y
X > A
Y > B

Is it possible to get that mapping in emulatorlauncher?

**Comment by fabricecaruso** [comment]
I don't really understand the question.... Input is read from es_settings.

**Comment by samiracho** [comment]
You mean es_inputs ?
np I'll keep working on the pr on my free time.

**Pull request merged**
