### PR TITLE
Add Russian localization in emulatorLauncher

### PR DESCRIPTION
**Pull request by TheDayG0ne**

### CODE REVIEW

**Comment by fabricecaruso** [comment]
I'm fine to merge the Resources.ru.resx thing, but you upgraded projets to dotnet48 and tools version 12.
We stay with dotnet 40 for now on purpose.
Can you revert those changes & please not upgrade projects ?

**Comment by TheDayG0ne** [comment]
projects updated automatically to dotnet 4.8, I opened the project in Visual Studio 2022

**Comment by TheDayG0ne** [comment]
Done.

**Comment by fabricecaruso** [comment]
the resx & designer.cs files are no more referenced in csproj

**Comment by TheDayG0ne** [comment]
Done.

**Pull request merged**
